---
- name: Creating a namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      k8s:
        kubeconfig: "stagingconfig"
        name: hopper # defining the namespace
        api_version: v1
        kind: Namespace
        state: present    # State=present when you need to create new object


