- hosts: localhost
  tasks:
    - name: create namespace
      k8s:
        kubeconfig: "stagingconfig"
        name: my-namespace
        api_version: v1
        kind: Namespace
        state: absent

