apiVersion: triliovault.trilio.io/v1
kind: Target
metadata:
  name: hopper-demo-s3-target
spec:
  type: ObjectStore
  vendor: AWS
  objectStoreCredentials:
    url: "https://s3.amazonaws.com"
    credentialSecret:
      name: demo-secret
      namespace: hopper
    bucketName: "bhtvault-bucket"
    region: "us-east-1"
  thresholdCapacity: 5Gi
